language: bash
sudo: false

matrix:
  allow_failures:
  include:

    - os: linux
      arch: amd64
      dist: bionic
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh -vv
    - os: linux
      arch: ppc64le
      dist: bionic
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
      script:
        - openssl version
        - sudo apt update && sudo apt install -y shellcheck;
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh -vv

    - os: osx
      osx_image: xcode10.1
      script:
        - openssl version
        - sh op_test.sh -vv

